# ML Zoomcamp 2025

# Numpy Arrays

Creating arrays

- np.zeros
- np.ones
- np.full
- np.repeat
- np.array
- np.arange

In [1]:
import numpy as np

Making one dimensional array

In [3]:
np.zeros(4)

array([0., 0., 0., 0.])

In [4]:
np.ones(4)

array([1., 1., 1., 1.])

In [7]:
np.full(4, 8)

array([8, 8, 8, 8])

In [8]:
np.array = [7, 8, 10, 9, 4]

In [2]:
a = np.array([7, 8, 10, 9, 4])
a

array([ 7,  8, 10,  9,  4])

In [3]:
a[2]

np.int64(10)

In [4]:
a[2] = 6
a

array([7, 8, 6, 9, 4])

In [7]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0, 6)

array([0, 1, 2, 3, 4, 5])

In [12]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Milti - Dimentional arrays

In [13]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
b[1, 1]

np.int64(5)

In [18]:
b[0]

array([1, 2, 3])

In [22]:
b[:, 1]

array([2, 5, 8])

Randomly generated arrays

In [23]:
np.random.rand(3, 3)

array([[0.67624461, 0.04257331, 0.86615677],
       [0.62158431, 0.4197813 , 0.66443887],
       [0.30171893, 0.03814092, 0.15237744]])

In [26]:
np.random.randint(low = -50, high = 50, size = (5, 2))

array([[ 46,  48],
       [-36, -42],
       [ 34,  -4],
       [-38,  11],
       [  0, -44]], dtype=int32)

In [28]:
np.random.seed(2)
np.random.rand(3, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482]])

In [36]:
np.random.randn(2, 2)

array([[-1.42121723, -0.1534952 ],
       [-0.26905696,  2.23136679]])

Element-wise operations

In [40]:
c = np.arange(5)
c

array([0, 1, 2, 3, 4])

In [41]:
c + 1

array([1, 2, 3, 4, 5])

In [42]:
(c + 1) * 2

array([ 2,  4,  6,  8, 10])

In [43]:
d = ((c + 1) * -1) ** 2
d

array([ 1,  4,  9, 16, 25])

In [44]:
c + d

array([ 1,  5, 11, 19, 29])

Comparison Operations

In [45]:
d

array([ 1,  4,  9, 16, 25])

In [46]:
d >= 10

array([False, False, False,  True,  True])

In [47]:
d > c

array([ True,  True,  True,  True,  True])

In [48]:
d > (c + 10)

array([False, False, False,  True,  True])

In [51]:
c[ c >= d]

array([], dtype=int64)

Summarizing Operation

In [53]:
c

array([0, 1, 2, 3, 4])

In [56]:
c.min()

np.int64(0)

In [57]:
c.max()

np.int64(4)

In [58]:
c.mean()

np.float64(2.0)

In [59]:
c.std()

np.float64(1.4142135623730951)

In [60]:
np.random.seed(3)
n = np.random.randn(5, 4)
n

array([[ 1.78862847,  0.43650985,  0.09649747, -1.8634927 ],
       [-0.2773882 , -0.35475898, -0.08274148, -0.62700068],
       [-0.04381817, -0.47721803, -1.31386475,  0.88462238],
       [ 0.88131804,  1.70957306,  0.05003364, -0.40467741],
       [-0.54535995, -1.54647732,  0.98236743, -1.10106763]])

In [61]:
n.min()

np.float64(-1.8634927033644908)

In [62]:
n.max()

np.float64(1.7886284734303186)

In [63]:
n.mean()

np.float64(-0.09041574746288811)

In [64]:
n.std()

np.float64(0.9690565489121703)

In [65]:
#There are other operations like looking at min for each column or sorting them, but I can look for them and learn them as I go